### ISSUE TITLE
Fix module paths in the repo

### ISSUE THREAD

**Issue by Rebecca-Qian** [facebookresearch/droidlet#117]
## Type of Issue

Select the type of issue:
- [ ] Bug report (to report a bug)
- [ ] Feature request (to request an additional feature)
- [ ] Tracker (I am just using this as a tracker)
- [x] Refactor request
- [ ] Documentation Ask

## Description

There are still a lot of `sys.path.append`s in the repo. I suggest we permanently add shared modules to `sys.path`. 2 ways to do this:
1.  `site` module, which reads a list of directories and appends them to the module search path
https://docs.python.org/3/library/site.html

2. `PYTHONPATH` environment variable
https://docs.python.org/3/tutorial/modules.html#the-module-search-path

My vote is option #1.

## Current Behavior

`sys.path` is manipulated in Python sessions with `sys.path.append`.

## Expected Behavior

Being able to globally import from any `base_agent` file. Solution can be a single `.pth` file containing directory paths to automatically import to `sys.path`  on initialization.

**Comment by soumith** [comment]
we should completely remove `sys.path.append` everywhere.

We now have a `setup.py`, so our development really should be to execute `python setup.py develop` and then do development.
