### ISSUE TITLE
Remove sys.path.append hacks in craftassist

### ISSUE THREAD

**Issue by Rebecca-Qian** [facebookresearch/droidlet#159]
## Type of Issue

Select the type of issue:
- [ ] Bug report (to report a bug)
- [ ] Feature request (to request an additional feature)
- [ ] Tracker (I am just using this as a tracker)
- [x] Refactor request
- [ ] Documentation Ask

## Description

This is a sub task for #117 
Related locobot PR: #151 

## Current Behavior

Let's remove all in session python path hacks and let `setup.py` handle finding packages.

## Expected Behavior

If we want to use code as a module, create an empty `__init__.py` in the parent directory. Do not change `PYTHONPATH`.

After code cleanup, run `python setup.py develop` and verify tests pass.

## Links to any relevant pastes or documents 

Packages discovered with `setuptools`: P176005401

**Comment by kavyasrinet** [comment]
Looks like this is now done with Soumith's latest fix to master
