### ISSUE TITLE
Incorrect db write for attention node

### ISSUE THREAD

**Issue by snyxan** [facebookresearch/droidlet#18]
## Type of Issue

Select the type of issue:
- [x] Bug report (to report a bug)
- [ ] Feature request (to request an additional feature)
- [ ] Tracker (I am just using this as a tracker)
- [ ] Documentation Ask

## Description

When create an attention node, these table columns get written: `TABLE_COLUMNS = ["uuid", "x", "y", "z", "type_name", "ref_type"]`. type_name field is filled with attender's eid. It 's name field which should be filled, right?

Check out this code snippet: https://github.com/facebookresearch/droidlet/blob/main/base_agent/memory_nodes.py#L530

This issue is found during deeper inspection into shadow memory data.

**Comment by aszlam** [comment]
sorry, am not sure I understand the problem?  https://github.com/facebookresearch/droidlet/blob/main/base_agent/memory_nodes.py#L509

**Comment by snyxan** [comment]
it's not if type_name is intentionally used for that purpose. Why not use `name` instead of `type_name`?
