### ISSUE TITLE
Json validator fails at lots of commands, seems like capitalization issue

### ISSUE THREAD

**Issue by snyxan** [facebookresearch/droidlet#184]
## Type of Issue

Select the type of issue:
- [x] Bug report (to report a bug)
- [ ] Feature request (to request an additional feature)
- [ ] Tracker (I am just using this as a tracker)
- [ ] Refactor request
- [ ] Documentation Ask

## Description

See those issues, seems like a capitalization issue.

#181 
#180 
#175 
#174 
#173

**Comment by Rebecca-Qian** [comment]
Standardized capitalization in datasets, fixed
