### ISSUE TITLE
sha1sum issue on Mac

### ISSUE THREAD

**Issue by kavyasrinet** [facebookresearch/droidlet#197]
## Type of Issue

Select the type of issue:
- [ ] Bug report (to report a bug)
- [x] Feature request (to request an additional feature)
- [ ] Tracker (I am just using this as a tracker)
- [ ] Refactor request
- [ ] Documentation Ask

## Description
When running the scripts : `./tools/data_scripts/compare_directory_hash.sh` or `./tools/data_scripts/tar_and_hash_datasets.sh` on Mac, I get:
```
kavyasrinet-mbp:droidlet kavyasrinet$ find craftassist/agent/datasets -type f ! -name '*checksum*' -not -path '*/\.*' -print0 | sort -z | xargs -0 sha1sum | sha1sum
-bash: sha1sum: command not found
xargs: sha1sum: No such file or directory

kavyasrinet@kavyasrinet-mbp droidlet % find craftassist/agent/datasets -type f ! -name '*checksum*' -not -path '*/\.*' -print0 | sort -z | xargs -0 sha1sum | sha1sum
zsh: command not found: sha1sum
xargs: sha1sum: No such file or directory
```
Tried with both `bash` and `zsh`

**Comment by Rebecca-Qian** [comment]
fixed in #249
