### ISSUE TITLE
Parser Report does not reflect model accuracy

### ISSUE THREAD

**Issue by Rebecca-Qian** [facebookresearch/droidlet#212]
## Type of Issue

Select the type of issue:
- [x] Bug report (to report a bug)
- [ ] Feature request (to request an additional feature)
- [ ] Tracker (I am just using this as a tracker)
- [ ] Refactor request
- [ ] Documentation Ask

## Description

Commands that should fail, are passing the NSP report. See P244425511

One explanation is that we're not including literals in tree similarity, but there are other model failures that aren't accounted for eg. missing keys, extra keys.

**Comment by kavyasrinet** [comment]
A major issue :
After successful download, when I run interactive script with "turn right" I get:
```
{'dialogue_type': 'HUMAN_GIVE_COMMAND', 'action_sequence': [{'action_type': 'DANCE', 'dance_type': {'body_turn': {'relative_yaw': {'fixed_value': '90'}}}}]}
```
but querying the model through the dialogue_manager of FakeAgent:
```
{'action_sequence': [{'dance_type': {'body_turn': {'relative_yaw': '-90'}}, 'action_type': 'DANCE'}], 'dialogue_type': 'HUMAN_GIVE_COMMAND'}
```

Even after successful download, the unittest still seems to be using the previous version of the model.
