### ISSUE TITLE
Bot keeps sending "I don't know what you're referring to" when asked to go to unknown object 

### ISSUE THREAD

**Issue by Rebecca-Qian** [facebookresearch/droidlet#221]
## Type of Issue

Select the type of issue:
- [x] Bug report (to report a bug)
- [ ] Feature request (to request an additional feature)
- [ ] Tracker (I am just using this as a tracker)
- [ ] Refactor request
- [ ] Documentation Ask

## Description

Bot sends "I don't know what you're referring to" 50 times when asked to come to an unknown object. See P255821253 for trace

## Steps to reproduce

Behavior was triggered by command "come to rebeccaqian"

## Links to any relevant pastes or documents 

P255821253

**Comment by aszlam** [comment]
closed in https://github.com/facebookresearch/droidlet/pull/231
