### ISSUE TITLE
Dashboard in Turk improvement

### ISSUE THREAD

**Issue by kavyasrinet** [facebookresearch/droidlet#271]
## Type of Issue

Select the type of issue:
- [ ] Bug report (to report a bug)
- [x] Feature request (to request an additional feature)
- [ ] Tracker (I am just using this as a tracker)
- [ ] Refactor request
- [ ] Documentation Ask

## Checklist

Use this checklist if you are using this issue as a tracker:

- [x] We should move the voxelJS to the right hand side of the screen
- [x] Move history to be below the interact App
- [x] Remove mic button from interact App
- [x] Remove the description about clicking on x when something is wrong from Interact App
- [x] remove the clickable feature from Interact App

**Comment by snyxan** [comment]
All the five are resolved in this commit: https://github.com/facebookresearch/droidlet/commit/1500416fdebe087e20dbcbf1545c19ebefbb5f28
