### ISSUE TITLE
Parser Issues - 01/25

### ISSUE THREAD

**Issue by Rebecca-Qian** [facebookresearch/droidlet#28]
## Model Stats

Validation accuracies:
- annotated: 60.3%
- templated: 96%
- templated filters: 95.9%

Dataset changes since last push: none

Config changes:
Finetuning encoder now (previously frozen), with`lr=10^-5` and `warmup=1000`, same as decoder side.
Encoder dropout set to 0.01. No word dropout, no label smoothing. Other configs unchanged.

## Sample outputs

Fixed from internal issue #1472
```
>>> get_beam_tree("what is the name of the thing closest to you")
{'dialogue_type': 'GET_MEMORY', 'filters': {'output': {'attribute': 'NAME'}, 'argval': {'ordinal': 'FIRST', 'polarity': 'MIN', 'quantity': {'attribute': {'linear_extent': {'source': {'reference_object': {'special_reference': 'SPEAKER'}}}}}}}}
```
Previous parse:
`{'dialogue_type': 'GET_MEMORY', 'filters': {'triples': [{'pred_text': 'has_tag', 'obj_text': 'name of the thing'}], 'output': 'TAG', 'memory_type': 'REFERENCE_OBJECT', 'location': {'reference_object': {'special_reference': 'AGENT'}, 'relative_direction': 'NEAR'}}}
`
Fixed from internal issue #1472
```
>>> get_beam_tree("what colour is the carpet")
{'dialogue_type': 'GET_MEMORY', 'filters': {'triples': [{'pred_text': 'has_name', 'obj_text': [0, [4, 4]]}], 'output': {'attribute': 'COLOUR'}}}
>>>
```
Previous parse:
`{'dialogue_type': 'HUMAN_GIVE_COMMAND', 'action_sequence': [{'filters': {'output': {'attribute': 'COLOUR'}, 'triples': [{'pred_text': 'has_name', 'obj_text': 'carpet'}]}}]}`

Fixed from internal issue #1472
```
>>> get_beam_tree("make two circles behind me")
{'dialogue_type': 'HUMAN_GIVE_COMMAND', 'action_sequence': [{'action_type': 'BUILD', 'location': {'reference_object': {'special_reference': 'SPEAKER'}, 'relative_direction': 'BACK'}, 'schematic': {'triples': [{'pred_text': 'has_name', 'obj_text': [0, [2, 2]]}], 'repeat': {'repeat_key': 'FOR', 'repeat_count': [0, [1, 1]]}}}]}
```
Previous parse:
`{'dialogue_type': 'HUMAN_GIVE_COMMAND', 'action_sequence': [{'action_type': 'BUILD', 'location': {'reference_object': {'special_reference': 'SPEAKER'}, 'relative_direction': 'BACK'}, 'repeat': {'repeat_key': 'FOR', 'repeat_count': 'two'}, 'schematic': {'triples': [{'pred_text': 'has_name', 'obj_text': 'circle'}], 'repeat': {'repeat_key': 'FOR', 'repeat_count': 'two'}}}]}`

Fixed from internal issue #1472
```
>>> get_beam_tree("point to the cube")
{'dialogue_type': 'HUMAN_GIVE_COMMAND', 'action_sequence': [{'action_type': 'DANCE', 'dance_type': {'point': {'location': {'reference_object': {'filters': {'triples': [{'pred_text': 'has_name', 'obj_text': [0, [3, 3]]}]}}}}}}]}
>>>
```
Previous parse:
`{'dialogue_type': 'HUMAN_GIVE_COMMAND', 'action_sequence': [{'action_type': 'MOVE', 'location': {'reference_object': {'filters': {'triples': [{'pred_text': 'has_name', 'obj_text': 'cube'}]}}}}]}`

**Comment by aszlam** [comment]
"move 1 step forward" -> {'dialogue_type': 'HUMAN_GIVE_COMMAND', 'action_sequence': [{'action_type': 'MOVE', 'location': {'reference_object': {}, 'text_span': '1 step forward'}}]}

**Comment by aszlam** [comment]
ttad pre-coref "turn right" -> {'dialogue_type': 'HUMAN_GIVE_COMMAND', 'action_sequence': [{'action_type': 'MOVE', 'location': {'reference_object': {'special_reference': 'AGENT'}, 'relative_direction': 'RIGHT'}}]}

**Comment by anuragprat1k** [comment]
ttad pre-coref "point to the jacket" -> {'dialogue_type': 'PUT_MEMORY', 'filters': {'triples': [{'pred_text': 'has_name', 'obj_text': 'jacket'}]}, 'upsert': {'memory_data': {'memory_type': 'TRIPLE', 'triples': [{'pred_text': 'has_tag', 'obj_text': 'to the jacket'}]}}}

**Comment by snyxan** [comment]
ttad pre-coref "point to the left of the cow" -> {'dialogue_type': 'HUMAN_GIVE_COMMAND', 'action_sequence': [{'action_type': 'DANCE', 'location': {'reference_object': {'filters': {'triples': [{'pred_text': 'has_name', 'obj_text': 'cow'}]}}, 'relative_direction': 'LEFT'}}]}

**Comment by snyxan** [comment]
ttad pre-coref "how tall be the cube" -> {'dialogue_type': 'GET_MEMORY', 'filters': {'triples': [{'pred_text': 'has_name', 'obj_text': 'cube'}], 'output': 'count'}}

**Comment by snyxan** [comment]
ttad pre-coref "what be the width of the cube" -> {'dialogue_type': 'GET_MEMORY', 'filters': {'triples': [{'pred_text': 'has_name', 'obj_text': 'cube'}], 'output': {'attribute': 'SIZE'}}}
