### ISSUE TITLE
Write pre coref resolve and span fill logical forms for unit tests

### ISSUE THREAD

**Issue by Rebecca-Qian** [facebookresearch/droidlet#284]
## Type of Issue

Select the type of issue:
- [ ] Bug report (to report a bug)
- [x] Feature request (to request an additional feature)
- [ ] Tracker (I am just using this as a tracker)
- [ ] Refactor request
- [ ] Documentation Ask

## Description

There's no way to validate parse trees used in unit tests currently, since they are written as postprocessed trees and do not conform to grammar spec.

We should really consider writing unit test action dictionaries standardized with logical forms in the datasets and grammar. This is important to prevent data regressions.

**Comment by kavyasrinet** [comment]
@Rebecca-Qian, the test_y_parsing_report handles parse trees before coref_resolve and span processing. Did you try those ?

**Comment by kavyasrinet** [comment]
Not sure if this is still a bug, I think we discussed this. Closing for now, can reopen later if we decide to discuss this again
