### ISSUE TITLE
Remove deprecated IAM accounts in s3

### ISSUE THREAD

**Issue by Rebecca-Qian** [facebookresearch/droidlet#310]
## Type of Issue

Select the type of issue:
- [x] Bug report (to report a bug)
- [ ] Feature request (to request an additional feature)
- [x] Tracker (I am just using this as a tracker)
- [ ] Refactor request
- [ ] Documentation Ask

## Description
There are currently several inactive [AWS IAM accounts](https://console.aws.amazon.com/iam/home#/users) in S3. Let's remove  accounts from former collaborators. Ideally we should also regenerate old access keys.

**Comment by kavyasrinet** [comment]
Confirming that I removed Danielle's, Dhiraj's and Ryan's accounts on my end.
