### ISSUE TITLE
[Turk][Bug Report] process chat before query for ground truth and greetings

### ISSUE THREAD

**Issue by Rebecca-Qian** [facebookresearch/droidlet#321]
## Type of Issue

Select the type of issue:
- [x] Bug report (to report a bug)
- [ ] Feature request (to request an additional feature)
- [ ] Tracker (I am just using this as a tracker)
- [ ] Refactor request
- [ ] Documentation Ask

## Description

Commands like "Hello?" are routed to the parser when they should be sent greetings responses. Same for "Can you do a dance?" which is in ground truth.

This requires a fix in dialogue manager.

## Links to any relevant pastes or documents 

From Turk logs:
```
Hello?|{'dialogue_type': 'NOOP'}
```

**Comment by Rebecca-Qian** [comment]
Update after discussing with @kavyasrinet :
preprocess does not lowercase or strip question marks
```
preprocess.preprocess_chat("Hello?")
'Hello ?'
```
looks like we need to add this ourselves, at least for ground truth/hard coded responses.

**Comment by kavyasrinet** [comment]
> looks like we need to add this ourselves, at least for ground truth/hard coded responses.

I don't think we should add these to ground truth. A better solution is : update the preprocessing script to handle these or try out a new tokenizer

**Comment by Rebecca-Qian** [comment]
> > looks like we need to add this ourselves, at least for ground truth/hard coded responses.
> 
> I don't think we should add these to ground truth. A better solution is : update the preprocessing script to handle these or try out a new tokenizer

Yeah, that's what I meant. Add this to the postprocessing ourselves.

**Comment by kavyasrinet** [comment]
Closing this too since this isn't a bug.
