### ISSUE TITLE
Fix test_model_script 

### ISSUE THREAD

**Issue by kavyasrinet** [facebookresearch/droidlet#35]
## Type of Issue

Select the type of issue:
- [x] Bug report (to report a bug)
- [ ] Feature request (to request an additional feature)
- [ ] Tracker (I am just using this as a tracker)
- [ ] Documentation Ask

## Description

Right now running the [test_model_script](https://github.com/facebookresearch/droidlet/blob/main/base_agent/ttad/ttad_transformer_model/test_model_script.py) fails on the transformers version. Creating this issue to check this again and make sure we can run this with the version of transformers being used in the agent env

**Comment by Rebecca-Qian** [comment]
Fixed in #36
