### ISSUE TITLE
*** AttributeError: 'RandomMemorySelector' object has no attribute 'memids'

### ISSUE THREAD

**Issue by kavyasrinet** [facebookresearch/droidlet#363]
## Type of Issue

Select the type of issue:
- [x] Bug report (to report a bug)
- [ ] Feature request (to request an additional feature)
- [ ] Tracker (I am just using this as a tracker)
- [ ] Refactor request
- [ ] Documentation Ask

## Description
Repro:
```
 fd = {
                                            "output": {"attribute": {"num_blocks": {"block_filters": {}}}}, "selector": {"return_quantity": {"random" : "1"}},
                                            "memory_type": "REFERENCE_OBJECT",
                                            "triples": [
                                                {"pred_text": "has_name", "obj_text": "sphere"},
                                            ],
                                        }
ipdb> get_filter(agent, fd)
```
1. There are two missing imports in `filter_helper.py`. I added:
```
from memory_filters import RandomMemorySelector
from word2number.w2n import word_to_num
```
2. After adding the imports I get : `*** AttributeError: 'RandomMemorySelector' object has no attribute 'memids'`

**Comment by kavyasrinet** [comment]
Fix here: https://github.com/facebookresearch/droidlet/pull/364

**Comment by aszlam** [comment]
closed in https://github.com/facebookresearch/droidlet/pull/364
