### ISSUE TITLE
running craftassist agent throws key errors

### ISSUE THREAD

**Issue by kavyasrinet** [facebookresearch/droidlet#377]
## Type of Issue

Select the type of issue:
- [x] Bug report (to report a bug)
- [ ] Feature request (to request an additional feature)
- [ ] Tracker (I am just using this as a tracker)
- [ ] Refactor request
- [ ] Documentation Ask

## Description

Detailed log here: https://www.internalfb.com/phabricator/paste/view/P413912944
Started getting this after rebasing this PR : https://github.com/facebookresearch/droidlet/pull/369 on main

**Comment by aszlam** [comment]
closed in https://github.com/facebookresearch/droidlet/pull/397
