### ISSUE TITLE
Replace "sent successfully" with green tick 

### ISSUE THREAD

**Issue by kavyasrinet** [facebookresearch/droidlet#378]
## Type of Issue

Select the type of issue:
- [ ] Bug report (to report a bug)
- [x] Feature request (to request an additional feature)
- [ ] Tracker (I am just using this as a tracker)
- [ ] Refactor request
- [ ] Documentation Ask

## Description

Right now, on a successful send of message in interact pane from dashboard to the agent process, we get a "Sent successfully" acknowledgement, show in the screenshot below:
<img width="1680" alt="1" src="https://user-images.githubusercontent.com/5814583/117731296-c30a9100-b1a2-11eb-9b35-1799272f479a.png">

We'd like for you to replace this with a green tick next to the message.
Right now, a successful status is set in the backend [here](https://github.com/facebookresearch/droidlet/blob/1f6a131c76d35cf5734ad74f3c22c19c381298fc/base_agent/loco_mc_agent.py#L124)

And the frontend receives it via [this](https://github.com/facebookresearch/droidlet/blob/1f6a131c76d35cf5734ad74f3c22c19c381298fc/base_agent/loco_mc_agent.py#L138) socket event.

Handles it [here](https://github.com/facebookresearch/droidlet/blob/dbed63f1e6539694f77771e4dd4ce026389ac98c/dldashboard/web/src/StateManager.js#L125) and [here](https://github.com/facebookresearch/droidlet/blob/dbed63f1e6539694f77771e4dd4ce026389ac98c/dldashboard/web/src/StateManager.js#L164)

Once set, this status is then rendered in the React component [here](https://github.com/facebookresearch/droidlet/blob/dbed63f1e6539694f77771e4dd4ce026389ac98c/dldashboard/web/src/components/Interact/Message.js#L155)

This feature request asks for replacing this way of setting a text based status by a solid green tick next to the shown message.

**Comment by anuragprat1k** [comment]
Done.
