### ISSUE TITLE
Replacing hardcoded ip:port in dashboard with actual ones

### ISSUE THREAD

**Issue by snyxan** [facebookresearch/droidlet#379]
## Type of Issue

Select the type of issue:
- [ ] Bug report (to report a bug)
- [x] Feature request (to request an additional feature)
- [ ] Tracker (I am just using this as a tracker)
- [ ] Refactor request
- [ ] Documentation Ask

## Description

Right now ip:port in dashboard is hardcoded as "localhost:8000". We should replace it with actual ip:port.

Similar to how it is set in turk-version branch: https://github.com/facebookresearch/droidlet/blob/yuxuans/mephisto_dashboard/dldashboard/web/src/StateManager.js#L75

## Checklist

Use this checklist if you are using this issue as a tracker:

- [ ] Task 1
- [ ] Task 2
- [ ] Task 3 ...

**Comment by soumith** [comment]
was fixed by Yuxuan already
