### ISSUE TITLE
Craftassist won't respond to human-given command 

### ISSUE THREAD

**Issue by snyxan** [facebookresearch/droidlet#497]
## Type of Issue

Select the type of issue:
- [x] Bug report (to report a bug)
- [ ] Feature request (to request an additional feature)
- [ ] Tracker (I am just using this as a tracker)
- [ ] Refactor request
- [ ] Documentation Ask

## Description

After parser/perception refactor, the craftassist agent won't respond to any human-given command in the game.

reported by @am-zhang 

## Current Behavior

Craftassist agent won't respond to human-given commands. All other parts are functioning well (e.g. agent can finish tasks - default task when idle)

## Expected Behavior

craftassist will respond to huamn-given commands.

## Steps to reproduce

Run agents in the game and give commands like: "hello", "build a cube"

**Comment by kavyasrinet** [comment]
Also reported by @MarcyLee

**Comment by kavyasrinet** [comment]
once fixed, (and because this slipped through the unit tests) can we also add a unit test for this so we test for this going forward ?

**Comment by kavyasrinet** [comment]
Closing this since this has now been fixed
