### ISSUE TITLE
Updates for autocomplete tool

### ISSUE THREAD

**Issue by kavyasrinet** [facebookresearch/droidlet#52]
## Type of Issue

The documentation should talk about - 
1. datasets folder should be fetched and updated before starting with the app and perhaps point to it
2. The README of template tool should mention auto_complete is in it
3.  Can I wipe out the `commands.txt` entirely ? I think this file should be blank / user should create from scratch
4. What is `args` in `python ~/droidlet/tools/data_processing/txt_to_JSON.py [args]` ?
5. I think step #1 and #4 should be run before running the backend and frontend ?
6. Nit to rename : `~/droidlet/tools/data_processing/txt_to_JSON.py` to something 
7. We need to pretty print the dictionaries
8. The location for where to run `python ~/droidlet/tools/data_processing/txt_to_JSON.py` should be mentioned
9. Fix the path for `annotations_dir_path` in the script in #8 
10. "point" inside "dance" doesn't work for autocomplete
11. Once we are over or under the index, either wipe out the command field or show a prompt saying "you are done annotating" . Right now, it keeps showing the last message and incrementing the count.
12. We should not track the files : `backend/command_dict_pairs.json` and `backend/commands.txt`.
13. when json validation fails, show a pop up.
14. Rename `autocomplete_annotation.txt` to `high_pri_commands.txt` in S3

Select the type of issue:
- [ ] Bug report (to report a bug)
- [ ] Feature request (to request an additional feature)
- [ ] Tracker (I am just using this as a tracker)
- [x] Documentation Ask

## Description

Detailed description of the requested feature/documentation ask/bug report.

## Current Behavior

Description of current behavior or functionality.

## Expected Behavior

Description of the expected behavior or functionality. In case of feature request, please add input and expected output.

## Steps to reproduce

Please add steps to reproduce the bug here along with the stack trace.

## Links to any relevant pastes or documents 

Please post links to any relevant documents that might contain any extra information.

## Checklist

Use this checklist if you are using this issue as a tracker:

- [ ] Task 1
- [ ] Task 2
- [ ] Task 3 ...

**Comment by Rebecca-Qian** [comment]
More feature requests from hack session
- [ ] Convert spans from text to array during annotation

Bug fixes
- [ ] Only upload recently annotated commands

**Comment by Rebecca-Qian** [comment]
Fixed in #74
