### ISSUE TITLE
Standardize exception handling for base_agent

### ISSUE THREAD

**Issue by anuragprat1k** [facebookresearch/droidlet#54]
## Type of Issue

We catch exceptions in a myriad of ways 
- catching but raising another exception anyway with a generic message (for eg https://github.com/facebookresearch/droidlet/blob/main/base_agent/dialogue_objects/get_memory_handler.py#L165)
- silently consuming it (for eg https://github.com/facebookresearch/droidlet/blob/main/base_agent/base_util.py#L89)
- print the error (https://github.com/facebookresearch/droidlet/blob/main/base_agent/save_and_fetch_commands.py#L19)

Standardize how to do exception handling. Do we want to just print a message to the log? Do we want to send the error message and maybe even the stack trace back to the dashboard? 

Scoping this to base_agent for a limited scope. 

Select the type of issue:
- [ ] Bug report (to report a bug)
- [x] Feature request (to request an additional feature)
- [ ] Tracker (I am just using this as a tracker)
- [ ] Documentation Ask

**Comment by soumith** [comment]
looks like I already gated re-raising immediately via `DEVMODE=1`: https://github.com/facebookresearch/droidlet/blob/0a59e13123e185466ae6879c98730eccdb84bc5e/base_agent/core.py#L21-L23

I'm going to just raise by default, and we can do more targeted catching as needed.
