### ISSUE TITLE
Extend data scripts to support Mac OS X users

### ISSUE THREAD

**Issue by Rebecca-Qian** [facebookresearch/droidlet#57]
## Type of Issue

Select the type of issue:
- [ ] Bug report (to report a bug)
- [x] Feature request (to request an additional feature)
- [ ] Tracker (I am just using this as a tracker)
- [ ] Documentation Ask

## Description

Data scripts require GNU systems, eg. `readlink -f` is not supported on mac. Update data scripts to support Mac users for local development. This is useful for dataset updates and annotation tools. 

## Current Behavior

All scripts under `tools/data_scripts` fail when run on Mac OS.

## Expected Behavior

Seamless installation and deployment that is platform agnostic.

## Checklist

- [ ] Extend fetch scripts for parser models and datasets
- [ ] Extend deploy scripts for parser models and datasets (may need to install GNU tar on mac)
- [ ] Extend hash comparison check

cc @kavyasrinet @snyxan @anuragprat1k @soumith

**Comment by Rebecca-Qian** [comment]
@soumith what's ETA on this? want to integrate it into autocomplete tool this week :)

**Comment by soumith** [comment]
hey, did my PR not work? I see the issue reopened

**Comment by soumith** [comment]
oh i see, you issued #165 to fix it.
