### ISSUE TITLE
NSP is disconnected in robotic agents

### ISSUE THREAD

**Issue by anuragprat1k** [facebookresearch/droidlet#577]
## Type of Issue

We have a `perceive` method (https://github.com/facebookresearch/droidlet/blob/main/agents/locobot/locobot_agent.py#L158) in the locobot_agent. But this overrides the `perceive` method in the base class `loco_mc_agent` (https://github.com/facebookresearch/droidlet/blob/main/agents/loco_mc_agent.py#L281) and hence the latter never gets called in the [core event loop](https://github.com/facebookresearch/droidlet/blob/1704279cb4ae0935586ed6b4b6768bd2860df7c1/agents/core.py#L25). The base class `perceive` is where the command processing happens. Since we are never traversing that path for robotic agents, commands don't work on the robot. Should be a simple fix. 

Select the type of issue:
- [x] Bug report (to report a bug)
- [ ] Feature request (to request an additional feature)
- [ ] Tracker (I am just using this as a tracker)
- [ ] Refactor request
- [ ] Documentation Ask

## Steps to reproduce

Send any command to the agent from the dashboard - 'turn right' for example. Agent doesn't respond because it doesn't process the command.

**Comment by kavyasrinet** [comment]
Yeah I think we should do what we are doing [here](https://github.com/facebookresearch/droidlet/blob/main/agents/craftassist/craftassist_agent.py#L234)
Calling `super().perceive()` should fix this

**Comment by anuragprat1k** [comment]
Fixed in https://github.com/facebookresearch/droidlet/pull/614
