### ISSUE TITLE
Turn right 45 degrees on craftassist doesn't work

### ISSUE THREAD

**Issue by jhan6501** [facebookresearch/droidlet#605]
## Type of Issue

Select the type of issue:
- [x] Bug report (to report a bug)
- [ ] Feature request (to request an additional feature)
- [ ] Tracker (I am just using this as a tracker)
- [ ] Refactor request
- [ ] Documentation Ask

## Description
On locobot setup, when telling the agent to turn right 45 degrees (or left 45 degrees), the robot doesn't turn (instead I think it tilts)

## Current Behavior
Robot tilts upwards a bit when told to turn right 45 degrees. 

## Expected Behavior
Robot is expected to turn right 45 degrees 

## Steps to reproduce
Startup locobot, navigate to web dashboard, then tell robot to 'turn right 45 degrees' - observe how the robot does not perform the expected action

**Comment by aszlam** [comment]
should be closed in https://github.com/facebookresearch/droidlet/pull/614
