### ISSUE TITLE
Downloading python dependencies takes a long time

### ISSUE THREAD

**Issue by hollisma** [facebookresearch/droidlet#622]
## Type of Issue

Select the type of issue:
- [ ] Bug report (to report a bug)
- [ ] Feature request (to request an additional feature)
- [ ] Tracker (I am just using this as a tracker)
- [ ] Refactor request
- [ ] Documentation Ask

## Description

On the circleci tests on locobot for the #601 PR, it takes longer than 10 minutes and times out when downloading dependencies from requirements.txt. The PR only introduces two dependencies (scipy and pycococreatortools) so I'm not sure what the cause is for the slow downloads. 

## Current Behavior

Locobot test fails due to timeout. 

## Expected Behavior

Locobot test should pass. 

## Steps to reproduce

To run the tests locally, run `export DOCKER_IMAGE=theh1ghwayman/locobot-assistant:8.0` and then `docker run --gpus all --name loco-img --ipc=host -v $(pwd):/shared -w /shared $DOCKER_IMAGE .circleci/locobot_tests.sh`. When I ran this, the downloads stalled on the face_recognition package for 20+ min. I added a release number to the requirements.txt file for face_recognition and then the download stalled on a different package. Perhaps the solution is to specify the releases to be downloaded.

**Comment by anuragprat1k** [comment]
Closing because fixed for now.
