### ISSUE TITLE
Standardize format of data in all ground truth files to be json

### ISSUE THREAD

**Issue by kavyasrinet** [facebookresearch/droidlet#79]
## Type of Issue
Data format update requested

Select the type of issue:
- [ ] Bug report (to report a bug)
- [x] Feature request (to request an additional feature)
- [ ] Tracker (I am just using this as a tracker)
- [ ] Documentation Ask

## Description

Currently the `high_pri_commands.txt` file under `ground_truth` has `json.dumps` for the dictionaries. I suggest we update the data format for all files under ground truth to have json format instead of string so we can get rid of [`ast.literal_eval`](https://github.com/facebookresearch/droidlet/blob/main/base_agent/nsp_dialogue_manager.py#L118) altogether and use `json.loads`.

**Comment by Rebecca-Qian** [comment]
Agree, thanks for creating issue
