### ISSUE TITLE
Upgrade SpaCy version requirement

### ISSUE THREAD

**Issue by soumith** [facebookresearch/droidlet#8]
## Type of Issue

Select the type of issue:
- [x] Bug report (to report a bug)
- [ ] Feature request (to request an additional feature)
- [ ] Tracker (I am just using this as a tracker)

## Current Behavior

When I ran `pip install -r requirements.txt`, it errored out while installing spacy's dependency `thinc` with the error:

```
l/miniconda3/envs/droidlet/include/python3.6m -c include/_cuda_shim.cu -o build/temp.linux-x86_64-3.6/include/_cuda_shim.o -arch=sm_30 --ptxas-options=-v -c --compiler-options '-fPIC'
  nvcc fatal   : Value 'sm_30' is not defined for option 'gpu-architecture'
```

The reason is that this old version of spacy/thinc aren't yet supporting CUDA 11.

We should upgrade the requirement if possible.

## Expected Behavior

SpaCy/ThinC get installed smoothly

## Steps to reproduce

On a machine with CUDA 11 activated, do `pip install -r requirements.txt` from the droidlet root directory.

**Comment by soumith** [comment]
The workaround that I had to use was `conda install spacy==2.0.12 -c conda-forge` which I believe precompiles ThinC without GPU support

**Comment by kavyasrinet** [comment]
Just cloned the repo from scratch and installed the requirements inside a conda env. Confirming that [this](https://github.com/facebookresearch/droidlet/blob/main/requirements.txt#L24) version works with the assistants.

**Comment by soumith** [comment]
it works if you activate a CUDA older than CUDA 11 on your machine (like your devfair).
On a machine where you have CUDA11 installed and thinc (spacy's dependency) detects it, it will fail to build with the above error.

**Comment by kavyasrinet** [comment]
Thanks!
I checked again and here's my nvidia-smi :
<img width="1213" alt="Screen Shot 2021-01-14 at 4 58 44 PM" src="https://user-images.githubusercontent.com/5814583/104667600-47348800-568b-11eb-9a2a-b8ffe60e641a.png">

and I did not do : `module load cuda/10.2` for example.
I can try reproducing this again from scratch to confirm and paste exact steps here.

**Comment by snyxan** [comment]
I'm able to reproduce this issue in my machine (cuda version: 11.0).

```nvcc --version```:
<img width="349" alt="Screen Shot 2021-01-19 at 1 57 08 PM" src="https://user-images.githubusercontent.com/34047968/105098027-538b5d00-5a5e-11eb-8641-cef9b92c0c82.png">

Steps to repro:
```
module load cuda/11.0
git clone --depth=1 --recursive https://github.com/facebookresearch/droidlet.git
cd droidlet
conda create -n droidlet_env python==3.7.4 pip numpy scikit-learn==0.19.1 pytorch torchvision
conda activate droidlet_env
pip install --no-cache-dir -r craftassist/requirements.txt
```

The trick here is to use `--no-cache-dir` to disable pip install cache. If so, install spacy/thinc will fail given cuda version >=11.0

**Comment by kavyasrinet** [comment]
@snyxan to we add the fix from the fork for neural_memory and close this one.
