### ISSUE TITLE
Test Pointing Default on Minecraft

### ISSUE THREAD

**Issue by anuragprat1k** [facebookresearch/droidlet#84]
## Type of Issue

Select the type of issue:
- [ ] Bug report (to report a bug)
- [ ] Feature request (to request an additional feature)
- [ ] Tracker (I am just using this as a tracker)
- [ ] Documentation Ask
- [x] Test

## Description

Test "where is the flower" (or any relevant object) in minecraft and see if the agent also points to it. I made a change where pointing is now a default action for a specific path in get_memory_handler - specifically when the attribute type is a location for the object being queried. 

More details at https://github.com/facebookresearch/droidlet/pull/17

**Comment by anuragprat1k** [comment]
Tagging @kavyasrinet @aszlam @snyxan to triage this.

**Comment by kavyasrinet** [comment]
I don't understand - is the ask to write a test for "where is the flower" or to check if this works in-game ?

**Comment by anuragprat1k** [comment]
> I don't understand - is the ask to write a test for "where is the flower" or to check if this works in-game ?

Just check that it works in game. Basically, we need to test the changes in https://github.com/facebookresearch/droidlet/pull/17 in minecraft. I don't have the mc agent setup yet, so if you guys can do it would be great. Or I can come around to it in a bit.

**Comment by kavyasrinet** [comment]
Sound good. 
Conforming that `GET_MEMORY` is calling a `Point` task after fetching from memory.
But `Point` is currently broken on Minecraft. Issue to track here: #95 .

**Comment by anuragprat1k** [comment]
Thanks. Closing this issue.
